In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('Advertising.csv')

In [6]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
df.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [10]:
X=df.drop('sales',axis=1)
y=df['sales']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [14]:
X_validat, X_holdout_test, y_validat, y_holdout_test = train_test_split(X_test, y_test, test_size=0.5, random_state=101)

In [18]:
len(X)

200

In [20]:
len(X_train)

140

In [22]:
len(X_validat)

30

In [24]:
from sklearn.ensemble import RandomForestRegressor

In [26]:
model=RandomForestRegressor(n_estimators=30,random_state=101)

In [28]:
model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=30, random_state=101)

In [30]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [32]:
validat_predictions=model.predict(X_validat)

In [34]:
validat_predictions

array([14.40333333,  5.47333333,  4.14      , 15.72666667, 11.66666667,
        9.93      , 10.83333333, 11.48      , 18.02      ,  7.60333333,
       10.9       , 21.44333333, 14.08333333,  7.53333333, 11.81333333,
        6.83      , 13.51      , 13.62      , 11.01333333,  7.99666667,
       12.53333333, 21.63      , 19.49      , 15.73      , 16.05666667,
       24.21666667, 20.17666667,  9.50666667, 14.50333333, 19.36333333])

In [36]:
mean_absolute_error(y_validat,validat_predictions)

0.6575555555555552

In [38]:
np.sqrt(mean_squared_error(y_validat,validat_predictions))

0.8542009478215644

In [40]:
holdout_predictions = model.predict(X_holdout_test)

In [42]:
holdout_predictions

array([10.98      ,  9.56666667, 11.74333333, 12.45      , 20.27      ,
        9.24      , 11.10333333, 18.71333333, 18.89666667,  9.63666667,
        6.38666667,  6.58      , 12.69      , 10.16      , 12.72      ,
       11.66666667, 12.71      , 19.21      , 24.64333333, 25.17      ,
        7.64      ,  9.64666667, 17.29      , 15.37      , 10.43666667,
       21.17666667,  9.82      ,  9.61      ,  8.49666667, 11.26333333])

In [44]:
mean_absolute_error(y_holdout_test,holdout_predictions)

0.5937777777777775

In [46]:
np.sqrt(mean_squared_error(y_holdout_test,holdout_predictions))

0.745323693040418

In [48]:
final_model = RandomForestRegressor(n_estimators=30,random_state=101)

In [50]:
final_model.fit(X,y)

RandomForestRegressor(n_estimators=30, random_state=101)

In [52]:
final_model.predict(X_test)

array([14.06      , 19.61333333, 12.17666667, 16.08      ,  9.28666667,
        6.84666667, 20.12      , 17.02      , 10.31333333, 19.75      ,
       10.71      , 14.18      , 11.72333333, 23.49      , 19.44666667,
        9.97333333, 12.20666667,  9.58      ,  8.70666667, 21.48333333,
        7.30333333, 18.88333333, 26.50666667, 24.40333333,  9.68666667,
       11.52333333, 20.53      ,  9.8       , 12.77      ,  9.09666667,
        8.89666667, 19.70333333, 11.27      ,  5.93333333, 17.52666667,
        9.77666667, 10.6       ,  9.97      ,  6.98333333, 10.59333333,
       12.66      , 10.31333333, 11.26333333,  7.31      , 11.78      ,
       11.14666667,  4.7       , 15.04333333, 13.28333333, 22.69333333,
       10.68      , 13.01      , 14.22      , 12.01666667, 10.88666667,
        4.04      , 25.59333333, 10.87      , 16.93333333, 15.28      ])

In [54]:
import h5py
import pickle

In [56]:
with h5py.File("advertising.h5", "w") as f:
    model_bytes = pickle.dumps(final_model)  # Convert model to bytes
    f.create_dataset("model", data=np.void(model_bytes))  # Store in HDF5 format

print("Model saved as advertising.h5")

Model saved as advertising.h5


In [60]:
pip install --upgrade scikit-learn

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/a1/a6/c5b78606743a1f28eae8f11973de6613a5ee87366796583fb74c67d54939/scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for threadpoolctl>=3.1.0 from https://files.pythonhosted.org/packages/4b/2c/ffbf7a134b9ab11a67b0cf0726453cedd9c5043a4fe7a35d1cefa9a1bcfb/threadpoolctl-3.5.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB 653.6 kB/s eta 0:00:17
   ---------------------------------------- 0.1/11.1 MB 550.5 kB/s eta 0:00:21
   ---------------------------------------- 0.1/11.1 MB 438.9 kB/s eta 0:00:26
   ------------------------------------

In [62]:
pip show scikit-learn

Name: scikit-learn
Version: 1.6.1
Summary: A set of python modules for machine learning and data mining
Home-page: 
Author: 
Author-email: 
License: BSD 3-Clause License

 Copyright (c) 2007-2024 The scikit-learn developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIB